version: '3.8'

services:
  # Django 应用服务
  web:
    build: .
    container_name: cardverification_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=CardVerification.settings
    depends_on:
      - db
      - redis
    networks:
      - cardverification_network
    restart: unless-stopped

  # PostgreSQL 数据库服务（可选，如果要替换SQLite）
  db:
    image: postgres:15-alpine
    container_name: cardverification_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cardverification
      - POSTGRES_USER=cardverification
      - POSTGRES_PASSWORD=cardverification123
    ports:
      - "5432:5432"
    networks:
      - cardverification_network
    restart: unless-stopped

  # Redis 缓存服务（可选）
  redis:
    image: redis:7-alpine
    container_name: cardverification_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cardverification_network
    restart: unless-stopped

  # Nginx 反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: cardverification_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - web
    networks:
      - cardverification_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  cardverification_network:
    driver: bridge
