# 生产环境 Docker Compose 配置
version: '3.8'

services:
  # Django 应用服务
  web:
    build: .
    container_name: cardverification_prod
    ports:
      - "8000:8000"
    volumes:
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
    restart: unless-stopped

volumes:
  media_volume:
