# Generated by Django 5.2.3 on 2025-06-12 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='密钥名称')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('rate_limit', models.IntegerField(default=60, verbose_name='频率限制(次/分钟)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, verbose_name='接口端点')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='请求数据')),
                ('response_code', models.IntegerField(verbose_name='响应状态码')),
                ('response_time', models.FloatField(verbose_name='响应时间(ms)')),
                ('call_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='调用时间')),
                ('success', models.BooleanField(default=True, verbose_name='调用成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apikey', verbose_name='API密钥')),
            ],
            options={
                'verbose_name': 'API调用记录',
                'verbose_name_plural': 'API调用记录',
                'ordering': ['-call_time'],
            },
        ),
    ]
