# Generated by Django 5.2.3 on 2025-06-12 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key', models.CharField(max_length=64, unique=True, verbose_name='卡密')),
                ('card_key_hash', models.CharField(max_length=40, unique=True, verbose_name='卡密哈希')),
                ('card_type', models.CharField(choices=[('time', '时间卡'), ('count', '次数卡')], max_length=10, verbose_name='卡密类型')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用'), ('expired', '已过期'), ('used_up', '已用完')], default='active', max_length=10, verbose_name='状态')),
                ('valid_days', models.IntegerField(blank=True, null=True, verbose_name='有效天数')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('total_count', models.IntegerField(blank=True, null=True, verbose_name='总次数')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('allow_multi_device', models.BooleanField(default=False, verbose_name='允许多设备')),
                ('max_devices', models.IntegerField(default=1, verbose_name='最大设备数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('first_used_at', models.DateTimeField(blank=True, null=True, verbose_name='首次使用时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '卡密',
                'verbose_name_plural': '卡密',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, verbose_name='设备ID')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='设备名称')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('first_bind_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次绑定时间')),
                ('last_active_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后活跃时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='卡密')),
            ],
            options={
                'verbose_name': '设备绑定',
                'verbose_name_plural': '设备绑定',
                'ordering': ['-last_active_time'],
                'unique_together': {('card', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('verification_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='验证时间')),
                ('success', models.BooleanField(default=True, verbose_name='验证成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('api_key', models.CharField(blank=True, max_length=64, verbose_name='API密钥')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='卡密')),
                ('device_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.devicebinding', verbose_name='设备绑定')),
            ],
            options={
                'verbose_name': '验证记录',
                'verbose_name_plural': '验证记录',
                'ordering': ['-verification_time'],
            },
        ),
    ]
